####################################################################################################
### Intersections between freshwater crabs and bioregions
### Checklist generated by Tan Zhi Wan.
### Global number of species from DecaNet eds. (2024). DecaNet. Accessed at https://www.decanet.info
### on 2024-12-26. doi:10.14284/600
###
### Charlie Marsh
### charliem2003@github
### 12/2024
###
### saves csv with the presence-absence of each species within each bioregion
####################################################################################################

#==================================================================================================#
#--------------------------------------------- Set-up ---------------------------------------------#
#==================================================================================================#

rm(list = ls())

### Libraries
library(dplyr)
library(tidyr)
library(stringr)

### Locations of data, scripts and results - ADJUST FOR YOUR STRUCTURE
projDir   <- "Diversity_and_endemism"                     # project dir
dataDir   <- file.path("Crab", "data", "directory")       # dir that contains the rangemaps data

### You shouldn't need to adjust these folders
resDir    <- file.path(projDir, "Intersections")          # dir to save results to
lookupDir <- file.path(resDir, "Look-up_tables")          # dir that contains look-up table for assigning bioregions

#==================================================================================================#
#------------------------------------------- Data prep --------------------------------------------#
#==================================================================================================#

### Read in cleaned freshwater crab data and remove crayfish - 488 species (global richness = 1764)
crabs <- read.csv(file.path(dataDir, "BTAS crab + crayfish data final.csv")) %>%
  filter(Family != "Parastacidae" & Genus != "Cherax") %>%
  as_tibble()

### There are some invalid UTF-8 characters that need replacing
crabs <- crabs %>%
  mutate(Secondary.division.region = sapply(Secondary.division.region, function(x) iconv(x, "UTF-8", "UTF-8", sub = ""))) %>%
  mutate(species = sapply(species, function(x) iconv(x, "latin1", "UTF-8", sub = "")))

### There is one typo in the name
crabs$species[crabs$species == "hainenensis bawanglingensis"] <- "hainanensis bawanglingensis"

### We have some subspecies - aggregate to species-level (keep earliest description year)
crabs <- crabs %>%
  mutate(Species = apply(., 1, function(x) paste(trimws(x["Genus"]),
                                                 strsplit(trimws(x["species"]), " ")[[1]][1],
                                                 sep = "_"))) %>%
  reframe(Family = unique(Family),
          Genus  = unique(Genus),
          Year   = min(Year),
          Distribution..Country.level. = paste(unique(Distribution..Country.level.), collapse = ", "),
          Secondary.division.region    = paste(unique(Secondary.division.region), collapse = ", "),
          .by = Species)

### Spreadsheet with codes to assign to countries and provinces to bioregions
bioregions <- read.csv(file.path(lookupDir, "country_codes_BTAS_freshwater_crabs.csv")) %>%
  select(Region, Bioregion, AsiaNative)

#==================================================================================================#
#------------------------------------ Determine intersections -------------------------------------#
#==================================================================================================#

### Separate out individual entries to unique rows
crabs <- crabs %>%
  separate_longer_delim("Distribution..Country.level.", delim = ", ")

### Append on Secondary division
crabs <- crabs %>%
  separate_longer_delim("Secondary.division.region", delim = ", ") %>%
  mutate(Region = apply(., 1, function(x) paste(x["Distribution..Country.level."],
                                                x["Secondary.division.region"]))) %>%
  mutate(Region = tolower(trimws(Region)))

### There should be no species with records in China and/or Japan with no other province info
filter(crabs, Distribution..Country.level. == "China" & Secondary.division.region == "")
filter(crabs, Distribution..Country.level. == "Japan" & Secondary.division.region == "")

### Likewise, there are no cases of country == Indonesia or Malaysia and no more detailed province info
filter(crabs, Distribution..Country.level. == "Malaysia" & Secondary.division.region == "")
filter(crabs, Distribution..Country.level. == "Indonesia" & Secondary.division.region == "")

### assign to BTAS bioregions
crabs <- crabs %>%
  left_join(bioregions, by = "Region", relationship = "many-to-many") %>%
  select(Species, Family, Genus, Year, Bioregion, AsiaNative)

### to check which countries aren't matched to Bioregions
# sort(unique(select(filter(wsc_region, is.na(Bioregion)), Region)$Region))

## which species are native to tropical asia
native <- crabs %>%
  group_by(Species) %>%
  reframe(native = max(AsiaNative, na.rm = TRUE)) %>%
  mutate(native = case_when(native >= 1 ~ 1,
                            native == 0 ~ 0))
crabs <- crabs %>%
  left_join(native, by = "Species") %>%
  filter(native == 1) %>%
  distinct()

### which species are endemic to tropical asia
endemic <- crabs %>%
  group_by(Species) %>%
  reframe(AsiaEndemic = any(is.na(Bioregion))) %>%
  mutate(AsiaEndemic = case_match(AsiaEndemic,
                                  FALSE ~ 1,
                                  TRUE  ~ 0))
crabs <- left_join(crabs, endemic, by = "Species")

### Filter only native intersections
crabs <- crabs %>%
  filter(AsiaNative == 1)

### convert to species x bioregion data frame
crabs <- crabs %>%
  select(Species, Genus, Family, Year, Bioregion, AsiaNative, AsiaEndemic) %>%
  filter(!duplicated(.))  %>%
  pivot_wider(id_cols = c(Species, Genus, Family, Year, AsiaEndemic),    
              names_from  = Bioregion,
              values_from = AsiaNative, 
              values_fill = 0) %>%
  relocate(Species, Genus, Family, Year, AsiaEndemic)

### total number of species native to region and number of species endemic to tropical asia
c(native = nrow(crabs),
  endemic = sum(crabs$AsiaEndemic))
colSums(crabs[, -c(1:5)])

### save results
write.csv(crabs, file.path(resDir, "Intersections", "Intersections_bioregions_freshwater_crabs.csv"),
          quote = FALSE, row.names = FALSE)

#==================================================================================================#
#----------------------------------------- Clean up memory ----------------------------------------#
#==================================================================================================#

rm(list = ls())
