####################################################################################################
### Intersections between Butterflies and bioregions
### Charlie Marsh
### Checklists generated by David Lohman and Peggie Djunijanti.
### Does not include data for Ryukus or Guangxi
### charliem2003@github
### 07/2024
###
### Taxonomy used:    Personal updates to Lamas, G. (2015) Catalog of the butterflies (Papilionoidea)
### Checklist used:   David Lohman and Peggie Djunijanti
### Endemism determined from:
###   Pinkert, Stefan; Barve, Vijay; Guralnick, Rob; Jetz, Walter (2022), Data for: Global geographic
###     and latitudinal variation in butterfly species richness captured through a comprehensive country-level
###     occurrence database, Dryad, Dataset, https://doi.org/10.5061/dryad.cz8w9gj47
###   Yau, E.Y.H., Jones, E.E., Tsang, T.P.N. et al. Spatial occurrence records and distributions of 
###     tropical Asian butterflies. Sci Data 12, 1004 (2025). https://doi.org/10.1038/s41597-025-05333-w
###
### saves csv with the presence-absence of each species within each bioregion
####################################################################################################

#==================================================================================================#
#--------------------------------------------- Set-up ---------------------------------------------#
#==================================================================================================#

rm(list = ls())

### Libraries
library(readxl)
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(sf)
library(terra)

### Locations of data, scripts and results
baseDir    <- "/mnt/Work"
spatialDir <- file.path(baseDir, "spatial_data", "biodiversity")       # dir that contains spatial data
# regionDir  <- file.path(baseDir, "NUS", "BTAS_data")                   # dir that contains the regions data
lohmanDir    <- file.path(spatialDir, "checklists", "butterflies", "Lohman")       # dir that contains the checklist data
sdmDir <- file.path(spatialDir, "sdms", "butterflies", "Yu")
occDir <- file.path(spatialDir, "occurrences", "butterflies", "Yu")
pinkertDir <- file.path(spatialDir, "checklists", "butterflies", "Pinkert_MOL")
gadmDir <- "/mnt/Work/spatial_data/regions/countries/GADM"
# resDir     <- file.path(baseDir, "NUS", "BTAS", "Intersections")       # dir to save results to
# funDir     <- file.path(baseDir, "NUS", "BTAS", "Analysis_functions")  # dir that contains the function scripts



### Locations of data, scripts and results - ADJUST FOR YOUR STRUCTURE
projDir   <- "Diversity_and_endemism"                          # project dir
dataDir    <- file.path("Butterfly", "data", "directory")    # dir that contains the checklist data
sdmDir     <- file.path("Yau", "SDM", "directory")           # dir containing SDM outputs from Yau
occDir     <- file.path("Yau", "point", "directory")         # dir containing ocurrence points from Yau
pinkertDir <- file.path("Pinkert", "checklist", "directory") # dir containing ocurrence points from Yau
gadmDir    <- file.path("GADM", "directory")                 # dir that contains GADM in equal-area projection (called 'GADM_410_land_Equal_Area.gpkg')

### You shouldn't need to adjust these folders
resDir  <- file.path(projDir, "Intersections")            # dir to save results to
funDir  <- file.path(projDir, "Analysis_functions")       # dir that contains the function scripts
dataDir <- file.path(projDir, "Data")                      # dir that contains the subregions data

#==================================================================================================#
#------------------------------------------- Data prep --------------------------------------------#
#==================================================================================================#

### Function for cleaning dates and extracting region info from inside brackets
source(file.path(funDir, "Discovery_rates", "clean_publication_dates.R"))

### Data for each region is stored in individual sheets in an xlsx file
filePath <- file.path(lohmanDir, "Asian_Butterfly_Distributions_20240702.xlsx")

### Read in and append individual data sheets - 4,757 species
all <- bind_rows(data.frame(Bioregion = "Indian_Subcontinent", read_xlsx(filePath, "SouthAsia_List")),
                 data.frame(Bioregion = "IndoChina",           read_xlsx(filePath, "Continental_SEAsia_List")),
                 data.frame(Bioregion = "Andamans",            read_xlsx(filePath, "AndamansNicobars_List")),
                 data.frame(Bioregion = "Malaya",              read_xlsx(filePath, "MalayPeninsula_List")),
                 data.frame(Bioregion = "Borneo",              read_xlsx(filePath, "Borneo_List")),
                 data.frame(Bioregion = "Palawan",             read_xlsx(filePath, "PalawanArea_List")),
                 data.frame(Bioregion = "Philippines",         read_xlsx(filePath, "PhilippinesNotPalawan_List")),
                 data.frame(Bioregion = "Sumatra",             read_xlsx(filePath, "Sumatra_Region_List")),
                 data.frame(Bioregion = "Java",                read_xlsx(filePath, "Java+Bali_List")),
                 data.frame(Bioregion = "Lesser_Sundas",       read_xlsx(filePath, "LesserSundas_List")),
                 data.frame(Bioregion = "Sulawesi",            read_xlsx(filePath, "Sulawesi_List")),
                 data.frame(Bioregion = "Maluku",              read_xlsx(filePath, "Maluku+NorthMaluku_List")),
                 data.frame(Bioregion = "New_Guinea",          read_xlsx(filePath, "New_Guinea_LIst"))) %>%
  as_tibble() %>%
  mutate(Species = gsub(" ", "_", Binomial_accepted)) %>%
  mutate(Year = clean_publication_dates(Species_authority, max = TRUE, first = FALSE)) %>%
  select(Species, Year, Bioregion) %>%
  distinct()

### Some manual cleaning of description dates 
all$Year[all$Species == "Bletogona_mycalesis"]    <- 1867
all$Year[all$Species == "Thermozephyrus_kubotae"] <- 2014
all$Year[all$Species == "Papilio_castor"]         <- 1842

### Global species list - 19,389 species
global <- read_excel(filePath, sheet = "GLOBAL_BUTTERFLY_LIST") %>%
  mutate(Species = gsub(" ", "_", Binomial_accepted)) %>%
  mutate(Genus = sapply(Binomial_accepted, function(x) unlist(strsplit(x, " ")[[1]][1]))) %>%
  select(Species, Genus, Family) %>%
  distinct()

### Data from Pinkert et al 2022 for determining endemism
pinkert <- read_csv(file.path(pinkertDir, "BttflyCCL_long_format_20220401.csv")) %>%
  distinct() %>%
  mutate(Species = gsub(" ", "_", ValidBinomial))

### GADM codes for converting Pinkert Alpha3 codes to countries
gadm_codes <- read.csv(file.path(pinkertDir, "gadm_codes.csv"))

### global GADM for masking out coastlines in SDM outputs
gadm <- st_read(file.path(gadmDir, "GADM_410_land_Equal_Area.gpkg"))

### Regions data
regions <- st_read(file.path(dataDir, "Bioregions_checklists.gpkg"))

#==================================================================================================#
#------------------------------------ Determine intersections -------------------------------------#
#==================================================================================================#

### Merge with taxonomy from global species list
all <- all %>%
  left_join(global,
            by = "Species")

### Pivot to wide format
all <- all %>%
  mutate(Presence = 1) %>%
  pivot_wider(id_cols     = c(Species, Genus, Family, Year),
              names_from  = Bioregion,
              values_from = Presence,
              values_fill = 0)

#==================================================================================================#
#-------------------------------- Determine tropical Asia endemism --------------------------------#
#==================================================================================================#

### First use the Pinkert data set. Keep only matching species and convert alpha3 codes to gadm names
pinkert <- pinkert %>%
  filter(Species %in% all$Species) %>%
  left_join(gadm_codes, join_by(Alpha.3 == GID_0))

### There is now a column defining whether each country is inside (1) or outside (0) tropical asia
### Summarise whether each species has any country information outside tropical asia
pinkert <- pinkert %>%
  reframe(AsiaEndemic   = min(TROPICAL_ASIA),
          COUNTRY       = unique(COUNTRY),
          .by           = Species)

### Pivot to species x country data frame. Remove columns for countries inside tropical Asia
pinkert <- pinkert %>%
  mutate(presence = 1) %>%
  pivot_wider(id_cols     = c(Species, AsiaEndemic),
              names_from  = COUNTRY,
              values_from = presence) %>%
  select(Species, AsiaEndemic, any_of(gadm_codes$COUNTRY[gadm_codes$TROPICAL_ASIA == 0]))

### Some species have only 'China' potential non-endemic info. Subset these species out
chinaOnly <- pinkert %>%
  mutate(n = rowSums(select(pinkert, -Species, -AsiaEndemic), na.rm = TRUE)) %>%
  filter(China == 1 & n == 1) %>%
  select(Species, AsiaEndemic, China, n)

### Otherwise keep other sets
pinkert <- pinkert %>%
  mutate(n = rowSums(select(pinkert, -Species, -AsiaEndemic), na.rm = TRUE)) %>%
  filter(!Species %in% chinaOnly$Species) %>%
  select(Species, AsiaEndemic, n)

#####################################################################
### Second, for china-only species try SDM outputs from Yu et al 2024

spList <- list.files(sdmDir, pattern = ".tif", full.names = FALSE)
spList <- sapply(spList, function(x) paste(strsplit(x, "[._]")[[1]][1:2], collapse = "_"))
spList <- spList[spList %in% chinaOnly$Species]

endemic <- data.frame(matrix(NA, ncol = nrow(regions) + 3))
names(endemic) <- c("Species", regions$Bioregion, "Total", "All_pts")
pb <- txtProgressBar(1, length(spList), style = 3)
for(i in 1:length(spList)) {
  setTxtProgressBar(pb, i)
  sp <- spList[i]

  ### read in species raster and convert to cell centroids
  spMap <- rast(file.path(sdmDir, paste0(gsub("_", ".", sp), "_ensemble_TSSbin.tif")))
  spMap <- as.points(spMap, values = TRUE) %>%
    st_as_sf() %>%
    rename(presence = paste0(gsub("_", ".", sp), "_EMmeanByTSS_mergedData_mergedRun_mergedAlgo")) %>%
    select(presence) %>%
    filter(presence == 1) %>%
    st_transform(st_crs(regions))

  ### Mask to GDM
  land <- st_intersects(spMap, gadm, sparse = FALSE)
  spMap <- spMap[land == TRUE, ]

  ### Intersect with bioregions
  intersection   <- as.data.frame(st_intersects(spMap, regions, sparse = FALSE))
  names(intersection) <- regions$Bioregion

  endemic[i,  1] <- sp
  endemic[i, -1] <- as.numeric(c(colSums(intersection), sum(intersection), nrow(spMap)))
}
endemic$Prop <- endemic$Total / endemic$All_pts

### For species without SDMs use points instead
occs <- read_csv(file.path(occDir, "OccurrenceRecords_22Jan2024_EY.csv")) %>%
  select(final_genus_species, lohman_final_genus_species, decimalLongitude, decimalLatitude) %>%
  mutate(Species_final  = gsub(" ", "_", final_genus_species)) %>%
  mutate(Species_lohman = gsub(" ", "_", lohman_final_genus_species)) %>%
  mutate(which_species = NA) %>%
  filter((Species_lohman %in% chinaOnly$Species) | (Species_final %in% chinaOnly$Species))

### There are two potential names to choose from. Try 'Lohman' first, then 'final'
occs$which_species[occs$Species_final  %in% chinaOnly$Species] <- "final"
occs$which_species[occs$Species_lohman %in% chinaOnly$Species] <- "lohman"
occs <- occs %>%
  mutate(Species = case_when(which_species == "lohman" ~ Species_lohman,
                             which_species == "final"  ~ Species_final))

### Loop through full species list
spList <- unique(occs$Species)
pts <- data.frame(matrix(NA, ncol = nrow(regions) + 3))
names(pts) <- c("Species", regions$Bioregion, "Total", "All_pts")
pb <- txtProgressBar(1, length(spList), style = 3)
for(i in 1:length(spList)) {
  setTxtProgressBar(pb, i)
  sp <- spList[i]

  ### filter species points
  spPts <- filter(occs, Species == sp)
  spPts <- st_as_sf(spPts, coords = c("decimalLongitude", "decimalLatitude"), crs = st_crs(4326)) %>%
    st_transform(st_crs(regions))

  ### Mask to GDM
  land <- st_intersects(spPts, gadm, sparse = FALSE)
  spPts <- spPts[land == TRUE, ]

  if(nrow(spPts) > 0) {
    ### Intersect with bioregions
    intersection   <- as.data.frame(st_intersects(spPts, regions, sparse = FALSE))
    names(intersection) <- regions$Bioregion

    pts[i,  1] <- sp
    pts[i, -1] <- as.numeric(c(colSums(intersection), sum(intersection), nrow(spPts)))
  }
}
pts$Prop <- pts$Total / pts$All_pts

### Apply a 95% threshold to account for overprediction and data errors
sdm <- endemic %>%
  mutate(endemic = case_when(Prop >= 0.95 ~ 1,
                             Prop <  0.95 ~ 0)) %>%
  mutate(type = "sdm")

pts <- pts %>%
  mutate(endemic = case_when(Prop >= 0.95 ~ 1,
                             Prop <  0.95 ~ 0)) %>%
  mutate(type = "pts")

### The points and SDMs largely agree with each other in terms of endemism
inner_join(pts, sdm, by = "Species", suffix = c("_pts", "_sdm")) %>%
  filter(endemic_pts != endemic_sdm) %>%
  select(Species) %>%
  as.vector()

### There are species with points without sdms, and vice-versa, so we need both sets
length(pts$Species[ pts$Species %in% sdm$Species])
length(sdm$Species[!sdm$Species %in% pts$Species])
length(pts$Species[!pts$Species %in% sdm$Species])

### Where there are both then default to the SDM prediction
both <- bind_rows(sdm, pts[!pts$Species %in% sdm$Species, ]) %>%
  rename(AsiaEndemic = endemic)
chinaOnly <- left_join(select(chinaOnly, Species),
                       select(both, Species, AsiaEndemic), by = "Species")

###########################################################################
### Third, for china only species without points or sdms use expert opinion

### There are 223 species remaining without points or sdms
sum(is.na(chinaOnly$AsiaEndemic))

### In these cases, use the expert opinion of David Lohman
manual <- read.csv(file.path(lohmanDir, "chinaOnly_species_DL.csv")) %>%
  mutate(Species = gsub(" ", "_", Species)) %>%
  mutate(AsiaEndemic = case_when(AsiaEndemic == "No"  ~ 0,
                                 AsiaEndemic == "Yes" ~ 1,
                                 AsiaEndemic == "Yes Asian Endemic; not found in China" ~ 1,
                                 AsiaEndemic == "Yes Asian Endemic; probably not found in China" ~ 1)) %>%
  select(Species, AsiaEndemic)

### Join the manual species up with the other China only species
chinaOnly <- left_join(chinaOnly, manual, by = "Species") %>%
  mutate(AsiaEndemic = rowSums(.[, c("AsiaEndemic.x", "AsiaEndemic.y")], na.rm = TRUE)) %>%
  select(Species, AsiaEndemic)

########################################################################################
### Fourth, finally for 178 species missing from Pinkert and Yu, also use expert opinion

missing <- read.csv(file.path(lohmanDir, "missing_Pinkert_species_DL.csv")) %>%
  filter(AsiaEndemic == "Unknown_missing_Pinkert") %>%
  mutate(Species = gsub(" ", "_", Species)) %>%
  mutate(AsiaEndemic = case_when(Asian.Endemic. == "No"  ~ 0,
                                 Asian.Endemic. == "Yes" ~ 1)) %>%
  select(Species, AsiaEndemic)

### And join everything back up with the pinkert data
endemism <- bind_rows(pinkert, chinaOnly, missing) %>%
  select(Species, AsiaEndemic)

################################################################
### Add the pinkert and china only data to the overall data frame

all <- all %>%
  left_join(endemism) %>%
  relocate(AsiaEndemic, .after = Year)

### total number of species native to region and number of species endemic to tropical asia
table(all$AsiaEndemic, useNA = "always")

### save results
write.csv(all, file.path(resDir, "Intersections", "Intersections_bioregions_butterflies.csv"),
          quote = FALSE, row.names = FALSE)

#==================================================================================================#
#----------------------------------------- Clean up memory ----------------------------------------#
#==================================================================================================#

rm(list = ls())
