####################################################################################################
### Intersections between Phasmids and bioregions
### Checklist cleaned and generated by Paul Tien Zhi Xian
### Charlie Marsh
### charliem2003@github
### 12/2024
###
### Taxonomy used:    https://phasmida.speciesfile.org/
### Checklist used:   https://phasmida.speciesfile.org/
###
### CITATION:
### Brock Paul D., Büscher Thies H., Baker Ed. 2024. Phasmida Species File Online. Retrieved on
###  2024-09-05 at https://phasmida.speciesfile.org/
###
### saves csv with the presence-absence of each species within each bioregion
####################################################################################################

#==================================================================================================#
#--------------------------------------------- Set-up ---------------------------------------------#
#==================================================================================================#

rm(list = ls())

### Libraries
library(dplyr)
library(tidyr)

### Locations of data, scripts and results - ADJUST FOR YOUR STRUCTURE
projDir   <- "Diversity"                                  # project dir
dataDir   <- file.path("Phasmid", "data", "directory")    # dir that contains the checklist data

### You shouldn't need to adjust these folders
resDir    <- file.path(projDir, "Intersections")          # dir to save results to
funDir    <- file.path(projDir, "Analysis_functions")     # dir that contains the function scripts
lookupDir <- file.path(resDir, "Look-up_tables")          # dir that contains look-up table for assigning bioregions

#==================================================================================================#
#------------------------------------------- Data prep --------------------------------------------#
#==================================================================================================#

### Function for cleaning dates and extracting region info from inside brackets
source(file.path(funDir, "Discovery_rates", "clean_publication_dates.R"))
source(file.path(funDir, "Intersections", "extractParantheses.R"))

### Read in cleaned phasmid data - 3576 rows (3548 species according to phasmida.speciesfile.org)
### Note, this includes subspecies which we will merge together later
all <- read.csv(file.path(dataDir, "updated-phasmid-data-done-cleaned.csv"), encoding = "UTF-8") %>%
  as_tibble() %>%
  select(AcceptedName, Author, Distribution)

### Spreadsheet of accepted names, families and genera for matching
taxon <- read.csv(file.path(dataDir, "updated-phasmid-data-done-cleaned-acceptedhighclassadded.csv")) %>%
  select(AcceptedName, Accepted.Genus, AcceptedFam) %>%
  distinct()

### Merge with taxon info and extract description year
all <- left_join(all, taxon, by = "AcceptedName") %>%
  mutate(Year   = clean_publication_dates(Author, max = TRUE, first = FALSE))

### Merge subspecies into species (but keep cases with subgenus in name) - 3,370 species globally
all <- all %>%
  mutate(Species = sapply(AcceptedName, function(x) {
    parts <- unlist(strsplit(x, " "))
    if(grepl("[(]", parts[2])) {
      Species <- paste(parts[1:3], collapse = " ")
    } else {
      Species <- paste(parts[1:2], collapse = " ")
    }
    return(Species)
  }
  ))

## In cases where subspecies were described in different years, take earliest description year
all <- all %>%
  reframe(Genus  = unique(Accepted.Genus),
          Family = unique(AcceptedFam),
          Year   = min(Year),
          Region = paste(unique(Distribution), collapse = ", "),
          .by = Species) %>%
  mutate(Species = gsub(" ", "_", Species))

### One species needs the description year added manually based on https://phasmida.speciesfile.org/
all$Year[all$Species == "Pylaemenes_scrupeus"] <- 2021

### And one species needs Genus and Family info
all$Genus [all$Species == "Phancloidea_baculus"] <- "Phancloidea"
all$Family[all$Species == "Phancloidea_baculus"] <- "Diapheromeridae"

### Spreadsheet with codes to assign to countries and provinces to bioregions
bioregions <- read.csv(file.path(lookupDir, "country_codes_BTAS_phasmids.csv")) %>%
  select(Region, Bioregion, AsiaNative)

#==================================================================================================#
#------------------------------------ Determine intersections -------------------------------------#
#==================================================================================================#

### Replace square brackets with normal brackets, and hard returns with spaces
all <- all %>%
  mutate(Region = gsub("[", "(", Region, fixed = TRUE)) %>%
  mutate(Region = gsub("]", ")", Region, fixed = TRUE)) %>%
  mutate(Region = gsub("[\n]", " ", Region))

### Extract province/island info from brackets and append to country name
all <- all %>%
  mutate(Region = sapply(Region, function(x) extractParantheses(x)))

### Separate out individual entries to unique rows
all <- all %>%
  separate_longer_delim(Region, delim = ", ") %>%
  mutate(Region = tolower(Region)) %>%
  mutate(Region = sapply(Region, function(x) trimws(x, "both")))

### Remove entries for introductions and unsures
all <- all %>%
  filter(!grepl("adventive|extinct|introduced|error", Region)) %>%
  filter(!grepl("[?]", Region, ignore.case = TRUE, fixed = FALSE))

### Out of 470 species with records in China and/or Japan there are 451 species in raw data with
### only 'China' or 'Japan' and no other province info -> exclude China and Japan
CN_JP_provinces <- c("guangdong", "hong kong", "macao")
length(unique(all$Species[grepl(paste0("china|japan|", CN_JP_provinces, collapse = "|"), all$Region)]))
all %>%
  filter(Species %in% all$Species[grepl(paste0("china|japan|", CN_JP_provinces, collapse = "|"), all$Region)]) %>%
  filter(!Species %in% all$Species[grepl(paste(CN_JP_provinces, collapse = "|"), all$Region)]) %>%
  summarise(length(unique(Species)))

### If country == Malaysia (135 sp), but more detailed province info also given, remove those rows
MalProvinces <- c("borneo", "labuan", "lombok", "sabah", "sarawak", "peninsular")
spMalaysia <- unique(all$Species[all$Species %in% all$Species[all$Region %in% c("malaysia")]])
for(i in 1:length(spMalaysia)) {
  sp <- filter(all, Species == spMalaysia[i])
  if(sum(grepl(paste(MalProvinces,  collapse = "|"), sp$Region)) >= 1) {
    all <- filter(all, Species != spMalaysia[i] | !Region %in% c("malaysia"))
  }
}

### There is only one case of 'Indonesia', and there is extra province info for that species. Remove
all <- filter(all, Region != "indonesia")

### Assign regional info to bioregions
all <- all %>%
  distinct() %>%
  left_join(bioregions, by = "Region", relationship = "many-to-many")

### which species are endemic to tropical asia
endemic <- all %>%
  group_by(Species) %>%
  reframe(AsiaEndemic = any(is.na(Bioregion))) %>%
  mutate(AsiaEndemic = case_match(AsiaEndemic,
                                  FALSE ~ 1,
                                  TRUE  ~ 0))
all <- all %>%
  select(-Region) %>%
  left_join(endemic, by = "Species")

### Filter only native intersections
all <- all %>%
  distinct() %>%
  filter(AsiaNative == 1)

### Pivot to wide format
all <- all %>%
  mutate(Presence = 1) %>%
  pivot_wider(id_cols     = c(Species, Genus, Family, Year, AsiaEndemic),
              names_from  = Bioregion,
              values_from = Presence,
              values_fill = 0)

### total number of species native to region and number of species endemic to tropical asia
table(all$AsiaEndemic)

### save results
write.csv(all, file.path(resDir, "Intersections", "Intersections_bioregions_phasmids.csv"),
          quote = FALSE, row.names = FALSE)

#==================================================================================================#
#----------------------------------------- Clean up memory ----------------------------------------#
#==================================================================================================#

rm(list = ls())
