####################################################################################################
### Intersections between Millipedes and bioregions
### Checklist cleaned and generated by Peter Decker
### Charlie Marsh
### charliem2003@github
### 12/2024
###
### Taxonomy used:    millibase.org
### Checklist used:   millibase.org
###
### CITATION:
### Sierwald, P.; Decker, P.; Spelda, J. (2024). MilliBase. Accessed at https://www.millibase.org
###   on 2024-11-20. doi:10.14284/370
###
### saves csv with the presence-absence of each species within each bioregion
####################################################################################################

#==================================================================================================#
#--------------------------------------------- Set-up ---------------------------------------------#
#==================================================================================================#

rm(list = ls())

### Libraries
library(readr)
library(dplyr)
library(tidyr)
library(stringr)

### Locations of data, scripts and results - ADJUST FOR YOUR STRUCTURE
projDir   <- "Diversity"                                  # project dir
dataDir   <- file.path("MilliBase", "data", "directory")  # dir that contains the checklist data

### You shouldn't need to adjust these folders
resDir    <- file.path(projDir, "Intersections")          # dir to save results to
funDir    <- file.path(projDir, "Analysis_functions")     # dir that contains the function scripts
lookupDir <- file.path(resDir, "Look-up_tables")          # dir that contains look-up table for assigning bioregions

#==================================================================================================#
#------------------------------------------- Data prep --------------------------------------------#
#==================================================================================================#

### Function for cleaning dates and extracting region info from inside brackets
source(file.path(funDir, "Discovery_rates", "clean_publication_dates.R"))

### Read in cleaned diplopod data
all <- read.csv(file.path(dataDir, "Diplopoda_distributions_2028-11-28.csv")) %>%
  as_tibble() 

### 12,287 species globally
length(unique(all$Species))

### Read in taxonomic info for getting authority year
acceptedList <- read.csv(file.path(dataDir, "Accepted taxa Aphia_taxlist_20241206.csv")) %>%
  as_tibble() %>%
  mutate(Year = sapply(Authority, function(x) clean_publication_dates(x))) %>%
  select(ScientificName, Genus, Family, Year) %>%
  distinct()

### There are 18 species where there are multiple authority years. Select earliest year
acceptedList <- acceptedList %>%
  reframe(Genus  = unique(Genus),
          Family = unique(Family),
          Year   = min(Year, na.rm = TRUE),
          .by = "ScientificName")

### Type locality data
taxon <- read.csv(file.path(dataDir, "Diplopoda_type localities_2024-11-27.csv")) %>%
  as_tibble()  %>%
  mutate(Year = sapply(Authority, function(x) clean_publication_dates(x))) %>%
  select(ScientificName, Genus, Family, Year) %>%
  distinct()

### Spreadsheet with codes to assign to countries and provinces to bioregions
bioregions <- read.csv(file.path(lookupDir, "country_codes_BTAS_diplopods.csv")) %>%
  select(Locality, Bioregion, AsiaNative)

#==================================================================================================#
#------------------------------------ Determine intersections -------------------------------------#
#==================================================================================================#

### Out of 605 species with records in China and/or Japan there are 324 species in raw data with
### only 'China' or 'Japan' and no other province info -> exclude China and Japan
CN_JP_provinces <- c("Aichi", "Beijing", "Boso", "Chongqing", "Ehime", "Fujian", "Fukui", "Fukuoka",
                     "Gansu", "Gifu", "Guizhou", "Gunma", "Hokkaido", "Honshu", "Hubei", "Hunan",
                     "Jiangsu", "Jiangxi", "Jilin", "Kagoshima", "Kochi", "Kyushu", "Nagano", "Nara",
                     "Qinghai", "Saitama", "Shaanxi", "Shiga", "Shizuoka", "Sichuan", "Tibet",
                     "Tochigi", "Tokyo", "Toyama", "Wakayama", "Xianggang", "Zhejiang", "Okinawa",
                     "Ryukyu Islands", "Guangdong", "Guangxi", "Hainan", "Hong Kong", "Yunnan")
length(unique(all$ScientificName_accepted[grepl(paste0("China|Japan|", CN_JP_provinces, collapse = "|"), all$Locality)]))
all %>%
  filter(ScientificName_accepted %in% all$ScientificName_accepted[grepl(paste0("China|Japan|", CN_JP_provinces, collapse = "|"), all$Locality)]) %>%
  filter(!ScientificName_accepted %in% all$ScientificName_accepted[grepl(paste(CN_JP_provinces, collapse = "|"), all$Locality)]) %>%
  summarise(length(unique(ScientificName_accepted)))

### We have no cases of entries of 'Malaysia' or 'Indonesia'
filter(all, Locality == "Malaysia")
filter(all, Locality == "Indonesia")

### Assign regional info to bioregions
all <- all %>%
  distinct() %>%
  left_join(bioregions, by = "Locality", relationship = "many-to-many")

### which species are native to tropical asia
native <- all %>%
  select(ScientificName_accepted, AsiaNative) %>%
  group_by(ScientificName_accepted) %>%
  mutate(AsiaNative = case_when(is.na(AsiaNative) ~ 0,
                                AsiaNative == 1   ~ 1)) %>%
  reframe(AsiaNative = max(AsiaNative, na.rm = TRUE))
all <- all %>%
  select(-AsiaNative) %>%
  left_join(native, by = "ScientificName_accepted") %>%
  filter(AsiaNative == 1) %>%
  distinct()

### which species are endemic to tropical asia
endemic <- all %>%
  group_by(ScientificName_accepted) %>%
  reframe(AsiaEndemic = any(is.na(Bioregion))) %>%
  mutate(AsiaEndemic = case_match(AsiaEndemic,
                                  FALSE ~ 1,
                                  TRUE  ~ 0))
all <- all %>%
  left_join(endemic, by = "ScientificName_accepted")

### Filter only native intersections
all <- all %>%
  filter(AsiaNative == 1) %>%
  filter(!is.na(Bioregion)) %>%
  select(ScientificName_accepted, Species, Genus, Family, AsiaEndemic, Bioregion) %>%
  distinct()

### Merge taxonomic info with locality info. First match up with the list of accepted names
year_family <- all %>%
  mutate(ScientificName = apply(., 1, function(x) { paste(x["Genus"], x["Species"], sep = " ") })) %>%
  select(ScientificName_accepted, ScientificName, Family, Genus, Species) %>%
  distinct() %>%
  mutate(Genus_accepted = sapply(ScientificName_accepted, function(x) { strsplit(x, " ")[[1]][1] }))

year_family <- year_family %>%
  left_join(acceptedList,
            join_by("ScientificName_accepted" == "ScientificName"),
            suffix = c("", ".x"),
            relationship = "many-to-many")

matchedAcceptedList <- year_family %>%
  select(ScientificName_accepted, Genus.x, Family.x, Year) %>%
  reframe(Genus  = unique(Genus.x),
          Family = unique(Family.x),
          Year   = min(Year, na.rm = TRUE),
          .by = "ScientificName_accepted") %>%
  filter(!is.na(Genus))

### There are 78 species not present in the accepted list
missing <- filter(year_family, !ScientificName_accepted %in% matchedAcceptedList$ScientificName_accepted)
missing %>% select(ScientificName_accepted) %>% unique() %>% nrow()

### Try matching with type localities list - first by ScientificName_accepted
matchedScientificName_accepted <- missing %>%
  select(ScientificName_accepted, ScientificName, Family, Genus, Species, Genus_accepted) %>%
  left_join(taxon, join_by("ScientificName_accepted" == "ScientificName"),
            suffix = c("", ".x"),
            relationship = "many-to-many")%>%
  reframe(Genus  = unique(Genus.x),
          Family = unique(Family.x),
          Year   = min(Year, na.rm = TRUE),
          .by = "ScientificName_accepted") %>%
  filter(!is.na(Genus))

### There are still 20 without matches
missing <- filter(missing, !ScientificName_accepted %in% matchedScientificName_accepted$ScientificName_accepted)
missing %>% select(ScientificName_accepted) %>% unique() %>% nrow()

### Try matching with type localities list but now by ScientificName_accepted
matchedScientificName <- missing %>%
  select(ScientificName_accepted, ScientificName, Family, Genus, Species, Genus_accepted) %>%
  left_join(taxon, join_by("ScientificName" == "ScientificName"),
            suffix = c("", ".x"),
            relationship = "many-to-many") %>%
  filter(!ScientificName_accepted %in% c("Aniulus (Hakiulus)", "Byzantorhopalum (Byzantorhopalum)")) %>%
  reframe(Genus  = unique(Genus.x),
          Family = unique(Family.x),
          Year   = min(Year, na.rm = TRUE),
          .by = "ScientificName_accepted") %>%
  filter(!is.na(Genus))

### There are 3 remaining missing cases. Add by hand
missing <- filter(missing, !ScientificName_accepted %in% matchedScientificName$ScientificName_accepted)
missing %>% select(ScientificName_accepted) %>% unique() %>% nrow()

missing$Genus[missing$ScientificName_accepted == "Julus celebensis"]  <- "Julus"
missing$Family[missing$ScientificName_accepted == "Julus celebensis"] <- "Julidae"
missing$Year[missing$ScientificName_accepted == "Julus celebensis"]   <- 1854

missing$Genus[missing$ScientificName_accepted == "Polydesmopeltis xanthotrichus"]  <- "Polydesmopeltis"
missing$Family[missing$ScientificName_accepted == "Polydesmopeltis xanthotrichus"] <- "Paradoxosomatidae"
missing$Year[missing$ScientificName_accepted == "Polydesmopeltis xanthotrichus"]   <- 1898

missing$Genus[missing$ScientificName_accepted == "Trachyjulus nordquisti"]  <- "Cambalopsidae"
missing$Family[missing$ScientificName_accepted == "Trachyjulus nordquisti"] <- "Trachyjulus"
missing$Year[missing$ScientificName_accepted == "Trachyjulus nordquisti"]   <- 1909

### Put them all together
taxon <- bind_rows(matchedAcceptedList,
                   matchedScientificName_accepted,
                   matchedScientificName,
                   missing) %>%
  select(ScientificName_accepted, Genus, Family, Year)

### Assume the year of description for Cystogonopus bicornis is that of parent species - https://millibase.org/aphia.php?p=taxdetails&id=947191
taxon$Year[taxon$ScientificName_accepted == "Cystogonopus bicornis"] <- 1942

### Orthomorpha bisculcata however has no description year in millibase. Set to NA
taxon$Year[taxon$ScientificName_accepted == "Orthomorpha bisculcata"] <- NA

### And amend one case where one accepted name has multiple entries
taxon$Genus [taxon$ScientificName_accepted == "Platyrhacus loriae"] <- "Platyrhachus"
taxon$Family[taxon$ScientificName_accepted == "Platyrhacus loriae"] <- "Platyrhacidae"
taxon$Year  [taxon$ScientificName_accepted == "Platyrhacus loriae"] <- 1895
taxon <- taxon %>%
  distinct()

### Pivot the intersection to wide format
all <- all %>%
  mutate(Presence = 1) %>%
  select(-Species, -Genus, -Family) %>%
  distinct() %>%
  pivot_wider(id_cols     = c(ScientificName_accepted, AsiaEndemic),
              names_from  = Bioregion,
              values_from = Presence,
              values_fill = 0)

### If Bioregion is 'Unknown', but there are other Bioregion info, remove the unknown classification
all <- all %>%
  relocate(Unknown, .after = Andamans) %>%
  rowwise() %>%
  mutate(Unknown = case_when(Unknown == 1 & any(Maluku:Andamans == 1) ~ 0,
                             .default = Unknown))

### Finally merge with the taxonomic info
all <- all %>%
  left_join(taxon,
            by = "ScientificName_accepted") %>%
  rename(Species = ScientificName_accepted) %>%
  mutate(Species = gsub(" ", "_", Species)) %>%
  relocate(Species, Genus, Family, Year)

### total number of species native to region and number of species endemic to tropical asia
table(all$AsiaEndemic)

### save results
write.csv(all, file.path(resDir, "Intersections", "Intersections_bioregions_diplopods.csv"),
          quote = FALSE, row.names = FALSE)

#==================================================================================================#
#----------------------------------------- Clean up memory ----------------------------------------#
#==================================================================================================#

rm(list = ls())
