####################################################################################################
### Intersections between freshwater crabs and bioregions
### Checklist generated by Tan Zhi Wan.
### Global number of species from DecaNet eds. (2024). DecaNet. Accessed at https://www.decanet.info
### on 2024-12-26. doi:10.14284/600
###
### Charlie Marsh
### charliem2003@github
### 12/2024
###
### Regions map used: Bioregions_checklists
### Taxonomy used:    ?
### Checklist used:   ?
###
### CITATION:
### ?
###
### saves csv with the presence-absence of each species within each bioregion
####################################################################################################

#==================================================================================================#
#--------------------------------------------- Set-up ---------------------------------------------#
#==================================================================================================#

rm(list = ls())

### Libraries
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(sf)

### Locations of data, scripts and results
baseDir   <- "/mnt/Work"
regionDir <- file.path(baseDir, "NUS", "BTAS_data", "Bioregions") # dir that contains the regions data
dataDir   <- file.path(baseDir, "spatial_data", "biodiversity", "checklists", "freshwater_crabs") # dir that contains the checklist data
resDir    <- file.path(baseDir, "NUS", "BTAS", "Intersections") # dir to save results to
gadmDir   <- file.path(baseDir, "spatial_data", "regions", "countries", "GADM", "GADM_4.1") # dir with gadm data
taxonDir  <- file.path(baseDir, "NUS", "BTAS", "BTAS_data", "taxonomies", "GBIF_backbone") # dir that contains GBIF taxonomic backbone

#==================================================================================================#
#------------------------------------------- Data prep --------------------------------------------#
#==================================================================================================#

### Read in cleaned freshwater crab data and remove crayfish - 488 species (global richness = 1764)
crabs <- read.csv(file.path(dataDir, "BTAS crab + crayfish data final.csv")) %>%
  filter(Family != "Parastacidae" & Genus != "Cherax") %>%
  as_tibble()

### There are some invalid UTF-8 characters that need replacing
crabs <- crabs %>%
  mutate(Secondary.division.region = sapply(Secondary.division.region, function(x) iconv(x, "UTF-8", "UTF-8", sub = ""))) %>%
  mutate(species = sapply(species, function(x) iconv(x, "latin1", "UTF-8", sub = "")))

### There is one typo in the name
crabs$species[crabs$species == "hainenensis bawanglingensis"] <- "hainanensis bawanglingensis"

### We have some subspecies - aggregate to species-level (keep earliest description year)
crabs <- crabs %>%
  mutate(Species = apply(., 1, function(x) paste(trimws(x["Genus"]),
                                                 strsplit(trimws(x["species"]), " ")[[1]][1],
                                                 sep = "_"))) %>%
  reframe(Family = unique(Family),
          Genus  = unique(Genus),
          Year   = min(Year),
          Distribution..Country.level. = paste(unique(Distribution..Country.level.), collapse = ", "),
          Secondary.division.region    = paste(unique(Secondary.division.region), collapse = ", "),
          .by = Species)

### Spreadsheet with codes to assign to countries and provinces to bioregions
bioregions <- read.csv(file.path(dataDir, "country_codes_BTAS_freshwater_crabs.csv")) %>%
  select(Region, Bioregion, AsiaNative)

#==================================================================================================#
#------------------------------------ Determine intersections -------------------------------------#
#==================================================================================================#

### Separate out individual entries to unique rows
crabs <- crabs %>%
  separate_longer_delim("Distribution..Country.level.", delim = ", ")

### Append on Secondary division
crabs <- crabs %>%
  separate_longer_delim("Secondary.division.region", delim = ", ") %>%
  mutate(Region = apply(., 1, function(x) paste(x["Distribution..Country.level."],
                                                x["Secondary.division.region"]))) %>%
  mutate(Region = tolower(trimws(Region)))

### There should be no species with records in China and/or Japan with no other province info
filter(crabs, Distribution..Country.level. == "China" & Secondary.division.region == "")
filter(crabs, Distribution..Country.level. == "Japan" & Secondary.division.region == "")

### Likewise, there are no cases of country == Indonesia or Malaysia and no more detailed province info
filter(crabs, Distribution..Country.level. == "Malaysia" & Secondary.division.region == "")
filter(crabs, Distribution..Country.level. == "Indonesia" & Secondary.division.region == "")

### assign to BTAS bioregions
crabs <- crabs %>%
  left_join(bioregions, by = "Region", relationship = "many-to-many") %>%
  select(Species, Family, Genus, Year, Bioregion, AsiaNative)

### to check which countries aren't matched to Bioregions
# sort(unique(select(filter(wsc_region, is.na(Bioregion)), Region)$Region))

## which species are native to tropical asia
native <- crabs %>%
  group_by(Species) %>%
  reframe(native = max(AsiaNative, na.rm = TRUE)) %>%
  mutate(native = case_when(native >= 1 ~ 1,
                            native == 0 ~ 0))
crabs <- crabs %>%
  left_join(native, by = "Species") %>%
  filter(native == 1) %>%
  distinct()

### which species are endemic to tropical asia
endemic <- crabs %>%
  group_by(Species) %>%
  reframe(AsiaEndemic = any(is.na(Bioregion))) %>%
  mutate(AsiaEndemic = case_match(AsiaEndemic,
                                  FALSE ~ 1,
                                  TRUE  ~ 0))
crabs <- left_join(crabs, endemic, by = "Species")

### Filter only native intersections
crabs <- crabs %>%
  filter(AsiaNative == 1)

### convert to species x bioregion data frame
crabs <- crabs %>%
  select(Species, Genus, Family, Year, Bioregion, AsiaNative, AsiaEndemic) %>%
  filter(!duplicated(.))  %>%
  pivot_wider(id_cols = c(Species, Genus, Family, Year, AsiaEndemic),    
              names_from  = Bioregion,
              values_from = AsiaNative, 
              values_fill = 0) %>%
  relocate(Species, Genus, Family, Year, AsiaEndemic)

### total number of species native to region and number of species endemic to tropical asia
c(native = nrow(crabs),
  endemic = sum(crabs$AsiaEndemic))
colSums(crabs[, -c(1:5)])

### save results
write.csv(crabs, file.path(resDir, "Intersections", "Intersections_bioregions_freshwater_crabs.csv"),
          quote = FALSE, row.names = FALSE)

####################################################################################################
### plot richness and turnover

regions <- st_read(file.path(regionDir, "Bioregions_checklists.gpkg")) %>%
  st_simplify(dTolerance = 1000)

rich <- data.frame(Bioregion = names(crabs[, -c(1:5)]),
                   Rich = colSums(crabs[, -c(1:5)]))
rich <- left_join(regions, rich, by = "Bioregion") %>%
  filter(!is.na(Rich))

ggplot() + 
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(colour = "black", fill = NA),
        # legend.position = c(0.1, 0.02),
        legend.position = "bottom",
        legend.text = element_text(size = 5),
        legend.title = element_text(size = 7),
        legend.justification = c("left", "bottom"),
        legend.key = element_blank()) +
  scale_fill_viridis_c(option = "C", name = NULL, trans = "log10") +
  guides(size = guide_legend(nrow = 2)) +
  scale_radius(range = c(3, 8),
               breaks = round(10 ^ seq(log10(min(rich$Rich)), log10(max(rich$Rich)), length.out = 5), 0),
               name = "Species Richness",
               trans = "log10") +
  geom_sf(data = rich, aes(fill = Rich)) + 
  geom_sf(data = st_centroid(rich),
          col = "black", pch = 21, aes(size = Rich, fill = Rich))

